CREATE TABLE Pessoa (
	ID integer PRIMARY KEY AUTOINCREMENT,
	Nome text,
	Foto text,
	Cargo text
);

CREATE TABLE Formação (
	ID integer PRIMARY KEY AUTOINCREMENT,
	Curso text,
	Duração date PRIMARY KEY AUTOINCREMENT,
	Descrição text PRIMARY KEY AUTOINCREMENT,
	Usuário text PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE Realizações (
	ID integer PRIMARY KEY AUTOINCREMENT,
	Duração date PRIMARY KEY AUTOINCREMENT,
	Projeto text PRIMARY KEY AUTOINCREMENT,
	Descrição text PRIMARY KEY AUTOINCREMENT,
	Usuário text PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE Informações (
	ID integer PRIMARY KEY AUTOINCREMENT,
	Email text,
	Telefone text PRIMARY KEY AUTOINCREMENT,
	CPF integer PRIMARY KEY AUTOINCREMENT,
	Endereço text PRIMARY KEY AUTOINCREMENT,
	Usuário text PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE Personalidade (
	ID integer PRIMARY KEY AUTOINCREMENT,
	Descrição text PRIMARY KEY AUTOINCREMENT,
	Usuário text PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE Habilidades (
	ID integer PRIMARY KEY AUTOINCREMENT,
	Descrição text PRIMARY KEY AUTOINCREMENT,
	Usuário text PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE Experiência (
	ID integer PRIMARY KEY AUTOINCREMENT,
	Descrição text PRIMARY KEY AUTOINCREMENT,
	Cargo text PRIMARY KEY AUTOINCREMENT,
	Duração date PRIMARY KEY AUTOINCREMENT,
	Nome da empresa text PRIMARY KEY AUTOINCREMENT,
	Usuário text PRIMARY KEY AUTOINCREMENT
);








